cil/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'cil'

urlpatterns = [
    #path('', views.Index.as_view(), name='index'),
    path(views.LogIn.as_view(), name='login'),
    path('adminauth/', views.AdminAuth.as_view(), name='adminauth'),
    path('guestauth/', views.GuestAuth.as_view(), name='guestauth'),
    path('guestadd/', views.GuestAdd.as_view(), name='guestadd'),
    path('guestedit/', views.GuestEdit.as_view(), name='guestedit'),
    path('guestupdate/?<int:profile>/', views.GuestUpdate.as_view(), name='guestupdate'),
    path('guestdelete/', views.GuestDelete.as_view(), name='guestdelete'),
    path('logout/', views.logoff, name='logout'),
    path('logs/', views.LogView.as_view(), name='logs'),
    path('admin/logout/', views.logoff, name='adminlogout')
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from cil import views

urlpatterns = [
    path('admin/logout/', views.logoff, name='adminlogout'),
    path('admin/', admin.site.urls),
    path('', include('cil.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cil/models.py
from django.db import models
from os.path import join


# Create your models here.

class Profile(models.Model):
    name = models.CharField(max_length=200)
    exp = models.CharField(max_length=20, null=True, blank=True)
    domain = models.CharField(max_length=1000,)
    designation = models.CharField(max_length=1000, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    biodata = models.FileField(null=True, blank=True)
    #file_url=models.CharField(max_length=200)

    def __str__(self):
        return self.name + '-' + self.domain

    def create(self, **kwargs):
        self.name = kwargs['name']
        self.exp = kwargs['exp']
        self.domain = kwargs['domain']
        self.designation = kwargs['designation']
        self.email = kwargs['email']
        self.phone = kwargs['phone']



class TempProfileAdd(models.Model):
    name = models.CharField(max_length=200)
    exp = models.CharField(max_length=20, null=True, blank=True)
    domain = models.CharField(max_length=1000)
    designation = models.CharField(max_length=1000, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    biodata = models.FileField(null=True, blank=True)
    #file_url=models.CharField(max_length=200)

    def __str__(self):
        return self.name + '-' + self.domain

    def create(self, **kwargs):
        self.name = kwargs['name']
        self.exp = kwargs['exp']
        self.domain = kwargs['domain']
        self.designation = kwargs['designation']
        self.email = kwargs['email']
        self.phone = kwargs['phone']


class TempProfileEdit(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    exp = models.CharField(max_length=20, null=True, blank=True)
    domain = models.CharField(max_length=1000)
    designation = models.CharField(max_length=1000, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    biodata = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name + '-' + self.domain

class TempProfileDelete(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.profile.name + '-' + self.profile.domain

    def create(self, obj):
        self.profile = obj

class Log(models.Model):
    name = models.CharField(max_length=50)
    department = models.CharField(max_length=50)
    time = models.DateTimeField(auto_now_add=True)

cil/forms.py
from django.forms import ModelForm
from .models import Profile


class GuestUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'exp', 'domain', 'designation', 'email', 'phone', 'biodata']

cil/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import login, authenticate, logout
from django.core.files.storage import FileSystemStorage
from .models import TempProfileAdd, Profile, TempProfileEdit, TempProfileDelete, Log
from .forms import GuestUpdateForm
from django.conf import settings
from prettytable import PrettyTable
import csv

file_name = "data.csv"


# Create your views here.

class Index(View):
    template_name = 'cil/index.html'

    def get(self, request):
        return render(request, self.template_name, {})


class LogView(View):
    template_name = "cil/logs.html"

    def get(self, request):
        if request.user.is_authenticated:
            return render(request, self.template_name, {})

    def post(self, request):
        data_set = request.POST
        name = data_set['name']
        department = data_set['department']
        obj = Log(name=name, department=department)
        obj.save()
        return redirect('cil:guestauth')


class LogIn(View):
    template_name = 'cil/login.html'

    def get(self, request):
        if request.user.is_authenticated:
            if request.user.is_superuser:
                return redirect('cil:adminauth')
        return render(request, self.template_name, {})

    def post(self, request):
        data_set = request.POST
        username = data_set["username"]
        password = data_set["password"]
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                if request.user.is_superuser:
                    return redirect('cil:adminauth')
                else:
                    return redirect('cil:logs')
        else:
            return render(request, self.template_name, {'err_ms': "Invalid Username or Password!"})


class AdminAuth(View):
    template_name = 'cil/adminauth.html'

    def get(self, request):
        dom = Profile.objects.all().values('domain').distinct().order_by('domain')
        pro = Profile.objects.all()
        file = open(settings.MEDIA_ROOT + "/" + file_name, "w")
        writer = csv.writer(file)

        if request.user.is_superuser:
            # t = PrettyTable(["Sr.No.", "Name", "Experience", "Designation", "Domain", "Email", "Phone"])
            t = ["Sr.No.", "Name", "Experience", "Designation", "Domain", "Email", "Phone"]
            writer.writerow(t)
            for i, d in enumerate(pro):
                writer.writerow([str(i + 1), d.name, str(d.exp), d.designation, d.domain, d.email, d.phone])
            #file.write(str(t))
            return render(request, self.template_name, {'pro': pro, 'dom': dom})

    def post(self, request):
        domain = request.POST['domain']
        if domain == "all":
            pro = Profile.objects.all()
        else:
            pro = Profile.objects.filter(domain=domain)
        dom = Profile.objects.all().values('domain').distinct().order_by('domain')

        file = open(settings.MEDIA_ROOT + "/" + file_name, "w")
        writer = csv.writer(file)

        t = ["Sr.No.", "Name", "Experience", "Designation", "Domain", "Email", "Phone"]
        writer.writerow(t)
        for i, d in enumerate(pro):
            writer.writerow([str(i + 1), d.name, str(d.exp), d.designation, d.domain, d.email, d.phone])
        return render(request, self.template_name, {'pro': pro, 'dom': dom, 'current': domain})


class GuestAuth(View):
    template_name = 'cil/guestauth.html'

    def get(self, request):
        dom = Profile.objects.all().values('domain').distinct().order_by('domain')
        pro = Profile.objects.all()

        file = open(settings.MEDIA_ROOT + "/" + file_name, "w")
        writer = csv.writer(file)
        if not request.user.is_superuser:
            t = ["Sr.No.", "Name", "Experience", "Designation", "Domain", "Email", "Phone"]
            writer.writerow(t)
            for i, d in enumerate(pro):
                writer.writerow([str(i + 1), d.name, str(d.exp), d.designation, d.domain, d.email, d.phone])
            return render(request, self.template_name, {'pro': pro, 'dom': dom})

    def post(self, request):
        domain = request.POST['domain']
        if domain == "all":
            pro = Profile.objects.all()
        else:
            pro = Profile.objects.filter(domain=domain)

        dom = Profile.objects.all().values('domain').distinct().order_by('domain')

        file = open(settings.MEDIA_ROOT + "/" + file_name, "w")
        writer = csv.writer(file)
        t = ["Sr.No.", "Name", "Experience", "Designation", "Domain", "Email", "Phone"]
        writer.writerow(t)
        for i, d in enumerate(pro):
            writer.writerow([str(i + 1), d.name, str(d.exp), d.designation, d.domain, d.email, d.phone])

        return render(request, self.template_name, {'pro': pro, 'dom': dom, 'current': domain})


class GuestAdd(View):
    template_name = 'cil/guestadd.html'

    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):
        data_set = request.POST
        if request.FILES:
            bio_file = request.FILES['biodata']
            if (not (bio_file.name.endswith('pdf')) and not (bio_file.name.endswith('doc')) and not (
                    bio_file.name.endswith('docx'))):
                return render(request, self.template_name,
                              {'ms': 'Please add your biodata in doc or docx or pdf format'})

        # fs = FileSystemStorage()
        domains = data_set['domain']
        if ',' in domains:
            domain_ls = domains.split(',')
            for i in range(len(domain_ls)):
                domain_add = domain_ls[i].strip()
                domain_add = domain_add.upper()
                print(i)
                obj = TempProfileAdd()
                obj.create(name=data_set['name'], exp=data_set['exp'], domain=domain_add,
                           designation=data_set['designation'], email=data_set['email'],
                           phone=data_set['phone'])
                if request.FILES:
                    obj.biodata = bio_file
                # obj.save()
                # name_split = bio_file.name.split('.')
                # file_name = 'TempAdd/' + str(obj.id) + '.' + name_split[1]
                # loc = fs.save(file_name, bio_file)
                # print(loc)
                # obj.file_url = loc
                obj.save()
        else:
            obj = TempProfileAdd()
            obj.create(name=data_set['name'], exp=data_set['exp'], domain=data_set['domain'].upper(),
                       designation=data_set['designation'], email=data_set['email'], phone=data_set['phone'])
            if request.FILES:
                obj.biodata = bio_file
            # obj.save()
            # name_split = bio_file.name.split('.')
            # file_name = 'TempAdd/' + str(obj.id) + '.' + name_split[1]
            # loc = fs.save(file_name, bio_file)
            # print(loc)
            # obj.file_url = loc
            obj.save()
        return render(request, self.template_name, {'ms': 'Added!'})


class GuestEdit(View):
    template_name = 'cil/guestedit.html'

    def get(self, request):
        obj = Profile.objects.all()
        return render(request, self.template_name, {'items': obj})

    def post(self, request):
        try:
            obj = Profile.objects.get(pk=request.POST.get('id'))
        except Profile.DoesNotExist:
            return render(request, self.template_name, {'ms': 'Name not found in Database', 'items': obj})
        base_url = reverse_lazy('cil:guestupdate', kwargs={'profile': obj.id})
        return redirect(base_url)


class GuestUpdate(View):
    template_name = 'cil/guestupdate.html'
    template_name_2 = 'cil/guestedit.html'

    def get(self, request, profile):
        obj = Profile.objects.get(id=profile)
        form = GuestUpdateForm(instance=obj)
        return render(request, self.template_name, {'form': form})

    def post(self, request, profile):
        pro = Profile.objects.all()
        data_set = request.POST
        profile_obj = Profile.objects.get(id=profile)
        form = GuestUpdateForm(instance=profile_obj)
        if request.FILES:
            bio_file = request.FILES['biodata']
            if (not (bio_file.name.endswith('pdf')) and not (bio_file.name.endswith('doc')) and not (
                    bio_file.name.endswith('docx'))):
                return render(request, self.template_name,
                              {'ms': 'Please add your biodata in doc or docx or pdf format', 'form': form})

        # fs = FileSystemStorage()
        # try:
        # TempProfileEdit.objects.get(profile=profile_obj)
        # except TempProfileEdit.DoesNotExist:
        obj = TempProfileEdit(name=data_set['name'], exp=data_set['exp'], domain=data_set['domain'],
                              designation=data_set['designation'],
                              email=data_set['email'], phone=data_set['phone'],
                              profile=profile_obj)
        if request.FILES:
            obj.biodata = bio_file
        obj.save()
        # name_split = bio_file.name.split('.')
        # file_name = 'TempEdit/' + str(obj.id) + '.' + name_split[1]
        # loc = fs.save(file_name, bio_file)
        # obj.file_url = loc
        # obj.save()
        return redirect('cil:guestedit')
        # return render(request, self.template_name_2,
        #             {'ms': 'Update request has already been submitted! Please wait for approval!', 'items': pro})


class GuestDelete(View):
    template_name = 'cil/guestdelete.html'

    def get(self, request):
        pro = Profile.objects.all()
        return render(request, self.template_name, {'pro': pro})

    def post(self, request):
        pro = Profile.objects.all()
        obj = Profile.objects.get(pk=request.POST['profid'])
        try:

cil/templates/cil/guestadd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>CIL - Add Request</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="all,follow" />
    <!-- Bootstrap CSS-->
    <link
      rel="stylesheet"
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <!-- Font Awesome CSS-->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous"
    />
    <!-- Google fonts - Popppins for copy-->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Poppins:300,400,800"
    />
    <!-- orion icons-->
    <link rel="stylesheet" href="{% static 'css/orionicons.css' %}" />
    <!-- theme stylesheet-->
    <link
      rel="stylesheet"
      href="{% static 'css/style.default.css' %}"
      id="theme-stylesheet"
    />
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'logo.png' %}" />
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
    ><![endif]-->
  </head>
  <body>
    <!-- navbar-->
    <header class="header">
      <nav class="navbar navbar-expand-lg px-4 py-4 bg-white shadow">
        <a href="#" class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead"
          ><i class="fas fa-align-left"></i></a
        ><a
          href="../"
          class="navbar-brand font-weight-bold text-uppercase text-base"
          >Centre for Inovative Learning</a
        >
        <!--<ul class="ml-auto d-flex align-items-center list-unstyled mb-0">
          <li class="nav-item dropdown ml-auto"><a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="logo.png" alt="Jason Doe" style="max-width: 2.5rem;" class="img-fluid rounded-circle shadow"></a>
            <div aria-labelledby="userInfo" class="dropdown-menu"><a href="#" class="dropdown-item"><strong class="d-block text-uppercase headings-font-family">Guest</strong></a>
              <div class="dropdown-divider"></div><a href="login.html" class="dropdown-item">Logout</a>
            </div>
          </li>
        </ul>-->
      </nav>
    </header>
    <div class="d-flex align-items-stretch">
      <div id="sidebar" class="sidebar py-3">
        <div
          class="text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family"
        >
          MAIN
        </div>
        <ul class="sidebar-menu list-unstyled">
          <li class="sidebar-list-item">
            <a href="{% url 'cil:guestauth' %}" class="sidebar-link text-muted"
              ><i class="o-home-1 mr-3 text-gray"></i><span>Home</span></a
            >
          </li>
          <li class="sidebar-list-item">
            <a
              href="{% url 'cil:guestadd' %}"
              class="sidebar-link text-muted active"
              ><i class="o-table-content-1 mr-3 text-gray"></i
              ><span>Add Request</span></a
            >
          </li>

          <li class="sidebar-list-item">
            <a href="{% url 'cil:guestedit' %}" class="sidebar-link text-muted"
              ><i class="o-table-content-1 mr-3 text-gray"></i
              ><span>Edit Request</span></a
            >
          </li>
          <li class="sidebar-list-item">
            <a
              href="{% url 'cil:guestdelete' %}"
              class="sidebar-link text-muted"
              ><i class="o-table-content-1 mr-3 text-gray"></i
              ><span>Delete Request</span></a
            >
          </li>

          <li class="sidebar-list-item">
            <a href="{% url 'cil:logout' %}" class="sidebar-link text-muted"
              ><i class="o-exit-1 mr-3 text-gray"></i><span>Logout</span></a
            >
          </li>
        </ul>
      </div>
      <div class="page-holder w-100 d-flex flex-wrap">
        <div class="container-fluid px-xl-5">
          <section class="py-5">
            <div class="row justify-content-center align-items-center">
              <div class="col-lg-6 mb-5">
                <div class="card">
                  <div class="card-header">
                    <h3 class="h6 text-uppercase mb-0">Add Request</h3>
                  </div>
                  <div class="card-body">
                    <p></p>
                    {% if ms %}
                    <h5>{{ ms }}</h5>
                    {% endif %}
                    <form
                      class="form-horizontal"
                      method="POST"
                      action=""
                      enctype="multipart/form-data"
                    >
                      {% csrf_token %}
                      <div class="form-group row">
                        <label class="col-md-3 form-control-label">Name</label>
                        <div class="col-md-9">
                          <input
                            id="inputHorizontalSuccess"
                            name="name"
                            placeholder="Name"
                            class="form-control form-control-success"
                          />
                        </div>
                      </div>
                      <div class="form-group row">
                        <label class="col-md-3 form-control-label">Email</label>
                        <div class="col-md-9">
                          <input
                            id="inputHorizontalSuccess"
                            name="email"
                            placeholder="Email Address"
                            class="form-control form-control-success"
                          />
                        </div>
                      </div>
                      <div class="form-group row">
                        <label class="col-md-3 form-control-label">Phone</label>
                        <div class="col-md-9">
                          <input
                            id="inputHorizontalSuccess"
                            name="phone"
                            placeholder="Phone"
                            class="form-control form-control-success"
                          />
                        </div>
                      </div>
                      <div class="form-group row">
                        <label class="col-md-3 form-control-label"
                          >Domain</label
                        >
                        <div class="col-md-9">
                          <input
                            id="inputHorizontalSuccess"
                            name="domain"
                            placeholder="Domain"
                            class="form-control form-control-success"
                          /><small class="form-text text-muted ml-3"
                            >Seperate using ','</small
                          >
                        </div>
                      </div>
                      <div class="form-group row">
                        <label class="col-md-3 form-control-label"
                          >Designation</label
                        >
                        <div class="col-md-9">
                          <input
                            id="inputHorizontalSuccess"
                            name="designation"
                            placeholder="Designation"
                            class="form-control form-control-success"
                          />
                        </div>
                      </div>
                      <div class="form-group row">
                        <label class="col-md-3 form-control-label"
                          >Experience</label
                        >
                        <div class="col-md-9">
                          <input
                            id="inputHorizontalSuccess"
                            name="exp"
                            placeholder="Experience"
                            class="form-control form-control-success"
                          />
                        </div>
                      </div>
                      <div class="form-group row">
                        <label class="col-md-3 form-control-label"
                          >Biodata/CV (Optional)</label
                        >
                        <div class="col-md-9">
                          <input
                            id="inputHorizontalSuccess"
                            name="biodata"
                            type="File"
                            class=""
                          /><small class="form-text text-muted ml-3"
                            >Upload in PDF, DOC or DOCX Format</small
                          >
                        </div>
                      </div>

                      <div class="form-group row">
                        <div class="col-md-9 ml-auto">
                          <input
                            type="submit"
                            value="Submit"
                            class="btn btn-primary"
                          />
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <footer
          class="footer bg-white shadow align-self-end py-3 px-xl-5 w-100"
        >
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 text-center text-md-left text-primary">
                <p class="mb-2 mb-md-0">Your company &copy; 2018-2020</p>
              </div>
              <div
                class="col-md-6 text-center text-md-right text-gray-400"
              ></div>
            </div>
          </div>
        </footer>
      </div>
    </div>

    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js' %}"></script>
    <script src="{% static 'js/charts-home.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>

cil/templates/cil/guestupdate1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Update form</h1>
{% if ms %}
<h1>{{ms}}</h1>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

cil/templates/cil/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Centre for Inovative Learning</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,800">
    <!-- orion icons-->
    <link rel="stylesheet" href="{% static 'css/orionicons.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'logo.png' %}" />
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
    ><![endif]-->
  </head>
  <body>
    <div class="page-holder d-flex align-items-center">
      <div class="container">
        <div class="row align-items-center py-5 justify-content-center">
          <div class="col-lg-8">
              <center>
                  <h1 class="text-base text-primary text-uppercase mb-2">Welcome to,</h1>
            <h2 class="mb-4">Centre for Inovative Learning</h2>
                  <a href="{% static 'readme.txt' %}" download><button class="btn btn-secondary px-5 m-3 mt-2 mb-5">Readme</button></a>
               <a  href="{% url 'cil:login' %}"><button class="btn btn-primary shadow px-5 m-3 mt-2 mb-5">Start</button></a>
            <p class="text-muted"><b>Developed By,</b><br>Kapil Mirchandani<br>Kunal Chadha<br>Manav Peshwani<br>Raghav Utpat<br><br><b>Mentored by,</b><br>Dr. Archana Ghotkar</b></p>
           
               
            </center>
          </div>
        </div>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>